---
title: "Terminal Tutorial"
format: pdf
editor: visual
---

# Introduction

## Shell Commands

<https://swcarpentry.github.io/shell-novice/01-intro.html>

+-----------------------+---------------------------------------------------------------------------------+
| Command               | Action                                                                          |
+=======================+=================================================================================+
| ls                    | shows what is in the directory                                                  |
+-----------------------+---------------------------------------------------------------------------------+
| ls -F                 | shows what things are in the directory                                          |
+-----------------------+---------------------------------------------------------------------------------+
| ls -l                 | shows directory contents in more detail                                         |
+-----------------------+---------------------------------------------------------------------------------+
| ls -R                 | shows everything inside the directory                                           |
+-----------------------+---------------------------------------------------------------------------------+
| man                   | shows manual for commands                                                       |
+-----------------------+---------------------------------------------------------------------------------+
| help                  | shows commands                                                                  |
+-----------------------+---------------------------------------------------------------------------------+
| cd ..                 | gets you to parent directory \[../\]                                            |
+-----------------------+---------------------------------------------------------------------------------+
| pwd                   | print working directory                                                         |
+-----------------------+---------------------------------------------------------------------------------+
| history               | shows command history                                                           |
+-----------------------+---------------------------------------------------------------------------------+
| mkdir                 | makes working directory                                                         |
|                       |                                                                                 |
| mkdir -p              | allows to make multiple folders at once                                         |
+-----------------------+---------------------------------------------------------------------------------+
| mv                    | mv \[old file name\] \[new file name\] --\> allows you to move and rename files |
+-----------------------+---------------------------------------------------------------------------------+
| rm -i                 | removes files (cannot get files back, permanently deleted)                      |
|                       |                                                                                 |
|                       | the -i double checks that you are deleting the thing you want to delete         |
+-----------------------+---------------------------------------------------------------------------------+
| rm -r -i              | allows you to delete directories                                                |
+-----------------------+---------------------------------------------------------------------------------+
| cp                    | copies directories/files                                                        |
|                       |                                                                                 |
|                       | cp \[file to copy\] \[new copy location and name\]                              |
+-----------------------+---------------------------------------------------------------------------------+
| nano \[filename.txt\] | opens up file in nano text editor                                               |
+-----------------------+---------------------------------------------------------------------------------+

# Xanadu

## cluster commands

<https://github.com/CBC-UCONN/CBC_Docs/wiki/Understanding-Xanadu#Xanadu_5>

+------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| commands                                             | action                                                                                                                  |
+======================================================+=========================================================================================================================+
| ssh                                                  | log in to head computer                                                                                                 |
| cpugliese\@xanadu-submit-ext.cam.uchc.edu            |                                                                                                                         |
+------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| srun \--partition=general \--qos=general \--pty bash | starts regular interactive session                                                                                      |
+------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| sinfo                                                | shows the node information (idle = not being used, mixed = some resources being used, alloc = all resources being used) |
+------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
