---
title: "Terminal Tutorial"
format: pdf
editor: visual
---

# Introduction

## Shell Commands

<https://swcarpentry.github.io/shell-novice/01-intro.html>

+-----------------------+---------------------------------------------------------------------------------+
| Command               | Action                                                                          |
+=======================+=================================================================================+
| ls                    | shows what is in the directory                                                  |
+-----------------------+---------------------------------------------------------------------------------+
| ls -F                 | shows what things are in the directory                                          |
+-----------------------+---------------------------------------------------------------------------------+
| ls -l                 | shows directory contents in more detail                                         |
+-----------------------+---------------------------------------------------------------------------------+
| ls -R                 | shows everything inside the directory                                           |
+-----------------------+---------------------------------------------------------------------------------+
| man                   | shows manual for commands                                                       |
+-----------------------+---------------------------------------------------------------------------------+
| help                  | shows commands                                                                  |
+-----------------------+---------------------------------------------------------------------------------+
| cd ..                 | gets you to parent directory \[../\]                                            |
+-----------------------+---------------------------------------------------------------------------------+
| pwd                   | print working directory                                                         |
+-----------------------+---------------------------------------------------------------------------------+
| history               | shows command history                                                           |
+-----------------------+---------------------------------------------------------------------------------+
| mkdir                 | makes working directory                                                         |
|                       |                                                                                 |
| mkdir -p              | allows to make multiple folders at once                                         |
+-----------------------+---------------------------------------------------------------------------------+
| mv                    | mv \[old file name\] \[new file name\] --\> allows you to move and rename files |
+-----------------------+---------------------------------------------------------------------------------+
| rm -i                 | removes files (cannot get files back, permanently deleted)                      |
|                       |                                                                                 |
|                       | the -i double checks that you are deleting the thing you want to delete         |
+-----------------------+---------------------------------------------------------------------------------+
| rm -r -i              | allows you to delete directories                                                |
+-----------------------+---------------------------------------------------------------------------------+
| cp                    | copies directories/files                                                        |
|                       |                                                                                 |
|                       | cp \[file to copy\] \[new copy location and name\]                              |
+-----------------------+---------------------------------------------------------------------------------+
| nano \[filename.txt\] | opens up file in nano text editor                                               |
+-----------------------+---------------------------------------------------------------------------------+
| cat \[filename\]      | looks like it prints out the file for viewing                                   |
+-----------------------+---------------------------------------------------------------------------------+

## shortcuts

|     |                   |
|-----|-------------------|
| \~  | home directory    |
| .   | current directory |
| ..  | one directory up  |
|     |                   |
|     |                   |

# Xanadu

## cluster commands

<https://github.com/CBC-UCONN/CBC_Docs/wiki/Understanding-Xanadu#Xanadu_5>

+------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| commands                                             | action                                                                                                                  |
+======================================================+=========================================================================================================================+
| ssh cpugliese\@xanadu-submit-ext.cam.uchc.edu        | log in to head computer                                                                                                 |
+------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| srun \--partition=general \--qos=general \--pty bash | starts regular interactive session                                                                                      |
+------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| sinfo                                                | shows the node information (idle = not being used, mixed = some resources being used, alloc = all resources being used) |
+------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| hostname                                             | tells you where you are                                                                                                 |
+------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| module list                                          | lists current modules loaded                                                                                            |
|                                                      |                                                                                                                         |
| module load                                          | load in new module                                                                                                      |
|                                                      |                                                                                                                         |
| module avail                                         | see the modules available                                                                                               |
+------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| sacc                                                 | shows what you have run                                                                                                 |
+------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| scancel \[job id\]                                   | can cancel jobs                                                                                                         |
|                                                      |                                                                                                                         |
| scancel -u \<user id\>                               | cancel all jobs under this user                                                                                         |
+------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+

# Storrs cluster

+-----------------------------------------+--------------------------------------------+
| commands                                | action                                     |
+=========================================+============================================+
| ssh clp20001\@hpc2.storrs.hpc.uconn.edu | logs into storrs log in node               |
+-----------------------------------------+--------------------------------------------+
| srun -n 1 -t 1:00:00 \--pty bash        | -n = number of cores                       |
|                                         |                                            |
|                                         | -t = how much time (1 hr)                  |
|                                         |                                            |
|                                         | \--mem=10G ---\> asks for amount of memory |
+-----------------------------------------+--------------------------------------------+
|                                         |                                            |
+-----------------------------------------+--------------------------------------------+

## Aliases (shortcuts)

+---------------+-----------------------------------------------------+
| ll            | ls -alF (long list)                                 |
+---------------+-----------------------------------------------------+
| ls            | ls -A                                               |
+---------------+-----------------------------------------------------+
| idev          | runs interactive session with 32G of memory         |
+---------------+-----------------------------------------------------+
| sq            | shows all that i'm running \[squeue -u cpugliese\]  |
+---------------+-----------------------------------------------------+
| numjob        |                                                     |
+---------------+-----------------------------------------------------+
