---
title: "Terminal Tutorial"
format: pdf
editor: visual
---

# Introduction

## Shell Commands

<https://swcarpentry.github.io/shell-novice/01-intro.html>

+-------------------------------------------+---------------------------------------------------------------------------------+
| Command                                   | Action                                                                          |
+===========================================+=================================================================================+
| ls                                        | shows what is in the directory                                                  |
+-------------------------------------------+---------------------------------------------------------------------------------+
| ls -F                                     | shows what things are in the directory                                          |
+-------------------------------------------+---------------------------------------------------------------------------------+
| ls -l                                     | shows directory contents in more detail                                         |
+-------------------------------------------+---------------------------------------------------------------------------------+
| ls -R                                     | shows everything inside the directory                                           |
+-------------------------------------------+---------------------------------------------------------------------------------+
| man                                       | shows manual for commands                                                       |
+-------------------------------------------+---------------------------------------------------------------------------------+
| help                                      | shows commands                                                                  |
+-------------------------------------------+---------------------------------------------------------------------------------+
| cd ..                                     | gets you to parent directory \[../\]                                            |
+-------------------------------------------+---------------------------------------------------------------------------------+
| pwd                                       | print working directory                                                         |
+-------------------------------------------+---------------------------------------------------------------------------------+
| history                                   | shows command history                                                           |
+-------------------------------------------+---------------------------------------------------------------------------------+
| mkdir                                     | makes working directory                                                         |
|                                           |                                                                                 |
| mkdir -p                                  | allows to make multiple folders at once                                         |
+-------------------------------------------+---------------------------------------------------------------------------------+
| mv                                        | mv \[old file name\] \[new file name\] --\> allows you to move and rename files |
+-------------------------------------------+---------------------------------------------------------------------------------+
| rm -i                                     | removes files (cannot get files back, permanently deleted)                      |
|                                           |                                                                                 |
|                                           | the -i double checks that you are deleting the thing you want to delete         |
+-------------------------------------------+---------------------------------------------------------------------------------+
| rm -r -i                                  | allows you to delete directories                                                |
+-------------------------------------------+---------------------------------------------------------------------------------+
| cp -i                                     | copies files                                                                    |
|                                           |                                                                                 |
|                                           | cp \[file to copy\] \[new copy location and name\]                              |
|                                           |                                                                                 |
|                                           | -i makes sure you don't overwrite a file with the same name                     |
+-------------------------------------------+---------------------------------------------------------------------------------+
| cp -r                                     | copies over all content in a directory                                          |
+-------------------------------------------+---------------------------------------------------------------------------------+
| nano \[filename.txt\]                     | opens up file in nano text editor                                               |
+-------------------------------------------+---------------------------------------------------------------------------------+
| cat \[filename\]                          | looks like it prints out the file for viewing                                   |
+-------------------------------------------+---------------------------------------------------------------------------------+
| ln -s \[original path\] \[new path name\] | creates a symlink                                                               |
+-------------------------------------------+---------------------------------------------------------------------------------+
| unzip                                     | unzips .zip file                                                                |
+-------------------------------------------+---------------------------------------------------------------------------------+
| touch \[filename\]                        | creates new file (and updates file timestamp)                                   |
+-------------------------------------------+---------------------------------------------------------------------------------+
| file \[file\]                             | tells what kind of file type a file is                                          |
+-------------------------------------------+---------------------------------------------------------------------------------+
| gzip                                      | g-zips file                                                                     |
+-------------------------------------------+---------------------------------------------------------------------------------+
| gunzip                                    | g-unzips file                                                                   |
+-------------------------------------------+---------------------------------------------------------------------------------+
| sudo                                      | lets you run any command with administrator privilages                          |
+-------------------------------------------+---------------------------------------------------------------------------------+

## shortcuts

|     |                    |
|-----|--------------------|
| \~  | home directory     |
| .   | current directory  |
| ..  | one directory up   |
| q   | exits manual page  |
| \-  | previous directory |

# Xanadu

## cluster commands

<https://github.com/CBC-UCONN/CBC_Docs/wiki/Understanding-Xanadu#Xanadu_5>

+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| commands                                                                                                                                                   | action                                                                                                                  |
+============================================================================================================================================================+=========================================================================================================================+
| ssh cpugliese\@xanadu-submit-ext.cam.uchc.edu                                                                                                              | (sshxan) log in to head computer, xanadu                                                                                |
|                                                                                                                                                            |                                                                                                                         |
|                                                                                                                                                            | password is og password, 1324!!!                                                                                        |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| ssh cpugliese\@login.hpc.cam.uchc.edu                                                                                                                      | (sshman) logs into mantis                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| srun --partition=general --qos=general --pty bash                                                                                                          | starts regular interactive session                                                                                      |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| sshfs cpugliese\@transfer.cam.uchc.edu:tmp/data/sra-seq/fastq /users/caprinapugliese/Documents/School/Uconn/2024-26_Grad_School/Dagilis-lab/cluster-mirror | use this node to transfer files                                                                                         |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| sinfo                                                                                                                                                      | shows the node information (idle = not being used, mixed = some resources being used, alloc = all resources being used) |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| hostname                                                                                                                                                   | tells you where you are                                                                                                 |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| module list                                                                                                                                                | lists current modules loaded                                                                                            |
|                                                                                                                                                            |                                                                                                                         |
| module load                                                                                                                                                | load in new module                                                                                                      |
|                                                                                                                                                            |                                                                                                                         |
| module avail                                                                                                                                               | see the modules available                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| sacc                                                                                                                                                       | shows what you have run                                                                                                 |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| scancel \[job id\]                                                                                                                                         | can cancel jobs                                                                                                         |
|                                                                                                                                                            |                                                                                                                         |
| scancel -u \<user id\>                                                                                                                                     | cancel all jobs under this user                                                                                         |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| screen                                                                                                                                                     | creates a screen (do this before starting interactive session)                                                          |
|                                                                                                                                                            |                                                                                                                         |
| screen -r                                                                                                                                                  | can help you get back to interactive session                                                                            |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| sattach \[job id\].0                                                                                                                                       | can merge two terminals together, can also probably help get back to an interactive session                             |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| scontrol show jobid \[job id\]                                                                                                                             | more info on job running                                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| wget                                                                                                                                                       | can help download packages                                                                                              |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| scp path/to/data.tar.gz user\@transfer.cam.uchc.edu:\<Path/to/Destination\>                                                                                | allows you to transfer files from laptop to cluster                                                                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+

# Storrs cluster

+-----------------------------------------+-------------------------------------------+
| commands                                | action                                    |
+=========================================+===========================================+
| ssh clp20001\@hpc2.storrs.hpc.uconn.edu | logs into storrs log in node              |
|                                         |                                           |
|                                         | (og uconn school password)                |
+-----------------------------------------+-------------------------------------------+
| srun -n 1 --pty bash                    | -n = number of cores                      |
|                                         |                                           |
|                                         | -t = how much time (1 hr)                 |
|                                         |                                           |
|                                         | --mem=10G ---\> asks for amount of memory |
+-----------------------------------------+-------------------------------------------+
|                                         |                                           |
+-----------------------------------------+-------------------------------------------+

## Aliases (shortcuts)

### on xanadu

+--------------------+--------------------------------------------------------------+
| ll                 | ls -alF (long list)                                          |
+--------------------+--------------------------------------------------------------+
| ls                 | ls -F                                                        |
+--------------------+--------------------------------------------------------------+
| bashi              | runs low mem interactive session                             |
+--------------------+--------------------------------------------------------------+
| bashmem            | runs 3g interactive session                                  |
+--------------------+--------------------------------------------------------------+
| sq                 | shows all that i'm running \[squeue -u cpugliese\]           |
+--------------------+--------------------------------------------------------------+
| numjob             | 'squeue 1 wc -1' --\> not entirely sure what this tells you? |
+--------------------+--------------------------------------------------------------+
|                    |                                                              |
+--------------------+--------------------------------------------------------------+
| cdf                | cd tmp/data/sra-seq/fastq                                    |
|                    |                                                              |
| cdseq              | cd tmp/data/sra-seq                                          |
+--------------------+--------------------------------------------------------------+
| scancel \[job id\] | cancels job that's running                                   |
+--------------------+--------------------------------------------------------------+

### on laptop

|           |                               |
|-----------|-------------------------------|
| sshxan    | xanadu login shortcut         |
| sshtransf | xanadu file transfer shortcut |
| cdwns     | shortcut to wns proj folder   |
|           |                               |
|           |                               |
|           |                               |
|           |                               |

`*` is for executables, `/` for directories, `=` for sockets, `>` for doors, `@` for symbolic links, `|` for FIFOs and nothing for regular files

sudo mkdir -p /usr/local/bin sudo rm -f /usr/local/bin/julia sudo ln -s /Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia /usr/local/bin/julia

1/12/26

mantis is only letting me type in one command if any before crashing and receiving a broken pipe error.

-   was able to get onto a node successfully but the same thing happened there

-   was still connected to the vpn, maybe that was the problem???

    -   looks like it was the vpn that was causing the problem