#!/bin/bash
#SBATCH --job-name=bcftools_stats
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 2
#SBATCH --mem=4G
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

########### script start

hostname
date

## load modules
module load bcftools/1.20

cd /home/FCAM/cpugliese/lab_wns/05_vcfs/01_orig-vcfs/only_pd/01_ploidy1

./vcf_analysis.sh only-pd.vcf.gz

########### script end