#!/bin/bash
#SBATCH --job-name=bcftools_stats
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 2
#SBATCH --mem=4G
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

########### script start

hostname
date

## load modules
module load bcftools/1.20
module load vcftools/0.1.16

## variables
INDIR=/home/FCAM/cpugliese/lab_wns/05_vcfs/01_orig-vcfs/only_pd/01_ploidy1
VCF=only-pd.vcf.gz
SCRIPT=/home/FCAM/cpugliese/wns/04_vcf/scripts/00_stats/01_vcf_analysis.sh

## run script
cd $INDIR
$SCRIPT $VCF ploidy1

########### script end